project:
  type: website

website:
  title: "Hiroaki Yutani"
  navbar:
    title: false
    logo-href: index.qmd
    logo: images/icon.jpg
    logo-alt: home
    search: false
    left:
      - text: about
        href: about.qmd
